var eliSubdivisionLabels = {
'PAR' : 'paragraph', 
'APP' : 'appendix', 
'OTH' : 'other', 
'ALN' : 'unnumbered paragraph', 
'SCT' : 'section', 
'CPT' : 'chapter', 
'FNP' : 'Concluding formulas', 
'CLS' : 'clause', 
'PRO' : 'protocol', 
'PRT' : 'part', 
'PNT' : 'point', 
'IDT' : 'indent', 
'TBG' : 'group of tables', 
'PBL' : 'preamble', 
'SUB' : 'subparagraph', 
'IMG' : 'image', 
'LGD' : 'legend', 
'TOC' : 'table of contents', 
'DCL' : 'declaration', 
'LST' : 'list', 
'CIT' : 'citation', 
'FGR' : 'figure', 
'PCD' : 'procedure', 
'NOT' : 'note', 
'END' : 'endnote', 
'ENC' : 'enacting terms', 
'ROW' : 'table row', 
'PTA' : 'point', 
'FTN' : 'footnote', 
'RCT' : 'recital', 
'ART' : 'article', 
'PTI' : 'point', 
'LLG' : 'line of legend', 
'CNV' : 'convention', 
'INP' : 'introductory part', 
'TXO' : 'old text', 
'ANX' : 'annex', 
'LTR' : 'letter', 
'TXN' : 'new text', 
'MNT' : 'minutes', 
'WRP' : 'closing part', 
'UNP' : 'unnumbered paragraph', 
'SNT' : 'sentence', 
'SFR' : 'scientific formula', 
'COL' : 'table column', 
'SBS' : 'subsection', 
'COR' : 'correction', 
'RUL' : 'rule', 
'AGR' : 'agreement', 
'CGR' : 'group of corrections', 
'ACT' : 'act', 
'DES' : 'description', 
'TAB' : 'table', 
'PAG' : 'page', 
'EXL' : 'exchange of letters', 
'FNA' : 'final act', 
'TIT' : 'title', 
'TIS' : 'title (subdivision)'
};
